//+------------------------------------------------------------------+
//| AI_Signal_Reader.mq5                                             |
//| Reads pre-computed AI signals from CSV and executes trades       |
//| in MT5 Strategy Tester.                                          |
//|                                                                  |
//| CSV format (generated by export_signals_mt5.py):                |
//|   open_time,direction,entry_price,sl_price,tp_price,atr,prob    |
//|   "2024.12.01 23:05", 1, 2648.63, 2645.55, 2665.58, 2.05, 0.74 |
//|                                                                  |
//| Config matches grid_0014:                                        |
//|   Risk 5%/trade | Max 4 concurrent | Threshold 0.70 (pre-filt.) |
//+------------------------------------------------------------------+
#property copyright "AI Signal Reader v1"
#property version   "1.00"
#property strict

//---- Inputs
input string   InpCSVFile       = "signals_for_mt5.csv";  // CSV filename (in MQL5/Files/)
input bool     InpReloadCsvOnNewBar = false; // Reload CSV on every new M5 bar for live append mode
input bool     InpSkipHistoricalSignalsOnInit = false; // Live mode: ignore already-closed bars on attach
input double   InpRiskPct       = 5.0;    // Risk % per trade
input int      InpMaxPositions  = 4;      // Max concurrent open positions
input double   InpMaxDailyLoss  = 12.0;  // Daily loss limit % of balance
input double   InpMaxRiskPct    = 2.0;   // Hard cap per order (% balance)
input double   InpMaxExposurePct= 6.0;   // Hard cap total open risk (% balance)
input double   InpMaxDDKillPct  = 15.0;  // Equity kill switch from initial balance
input double   InpMaxPeakDDKillPct = 0.0;// Equity kill switch from peak equity (0=disabled)
input double   InpTargetBalanceStop = 0.0;// Stop sleeve when balance/equity reaches this target (0=disabled)
input double   InpMinEntryDriftR= -999.0; // Min fill drift from signal entry, in original SL R
input double   InpMaxEntryDriftR= 999.0;  // Max fill drift from signal entry, in original SL R
input bool     InpTrailingEnabled = true; // Enable breakeven/trailing SL management
input double   InpBreakevenRR     = 0.5;  // Move SL to entry after this R
input double   InpTrailActivationRR = 1.0;// Start ATR trail after this R
input double   InpTrailAtrMultiple = 1.0; // Trail distance = ATR * this multiple
input int      InpMaxHoldBars     = 0;    // Close positions after this many M5 bars (0=disabled)
input bool     InpCloseOnStop   = true;  // Close positions when daily/kill stop trips
input int      InpMagic         = 13001;  // Magic number
input bool     InpVerbose       = false;  // Print debug per signal

//---- Internal
#define MAX_SIGNALS 100000

struct SignalRow {
    datetime signal_time;   // bar open_time from CSV
    int      direction;     // 1=BUY, -1=SELL
    double   entry_price;   // bar close (reference only)
    double   sl_price;
    double   tp_price;
    double   atr;
    double   prob;
};

SignalRow g_signals[];
int       g_sig_count   = 0;
int       g_sig_cursor  = 0;   // scan from here forward (signals sorted by time)

datetime  g_last_bar    = 0;
datetime  g_last_processed_signal_time = 0;
double    g_day_loss    = 0.0;
datetime  g_today       = 0;
double    g_initial_balance = 0.0;
double    g_day_start_balance = 0.0;
double    g_peak_equity = 0.0;
bool      g_day_blocked = false;
bool      g_killed = false;
datetime  g_last_stop_log = 0;

ulong  g_pos_tickets[];
double g_pos_initial_risk[];
double g_pos_atr[];
datetime g_pos_open_time[];

//+------------------------------------------------------------------+
//| Utility: count open positions by magic                           |
//+------------------------------------------------------------------+
int CountOpenPositions() {
    int cnt = 0;
    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        if (PositionGetTicket(i) > 0 &&
            PositionGetInteger(POSITION_MAGIC) == InpMagic &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
            cnt++;
    }
    return cnt;
}

//+------------------------------------------------------------------+
//| Risk helpers                                                      |
//+------------------------------------------------------------------+
double PriceRiskAmount(double volume, double entry, double sl) {
    double tick_val  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    double dist = MathAbs(entry - sl);
    if (volume <= 0 || dist <= 0 || tick_val <= 0 || tick_size <= 0) return 0.0;
    return (dist / tick_size) * tick_val * volume;
}

double PositionRiskAmount() {
    if (PositionGetInteger(POSITION_MAGIC) != InpMagic) return 0.0;
    if (PositionGetString(POSITION_SYMBOL) != _Symbol) return 0.0;
    double volume = PositionGetDouble(POSITION_VOLUME);
    double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
    double sl = PositionGetDouble(POSITION_SL);
    if (sl <= 0.0) return -1.0;
    return PriceRiskAmount(volume, open_price, sl);
}

double TotalOpenRisk(bool &unknown_risk) {
    unknown_risk = false;
    double total = 0.0;
    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        ulong ticket = PositionGetTicket(i);
        if (ticket == 0) continue;
        if (!PositionSelectByTicket(ticket)) continue;
        double risk = PositionRiskAmount();
        if (risk < 0.0) {
            unknown_risk = true;
        } else {
            total += risk;
        }
    }
    return total;
}

int FindPositionMeta(ulong ticket) {
    for (int i = 0; i < ArraySize(g_pos_tickets); i++) {
        if (g_pos_tickets[i] == ticket) return i;
    }
    return -1;
}

void RegisterPositionMeta(double entry, double sl, double atr, datetime open_time) {
    double best_diff = DBL_MAX;
    ulong best_ticket = 0;
    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        ulong ticket = PositionGetTicket(i);
        if (ticket == 0 || !PositionSelectByTicket(ticket)) continue;
        if (PositionGetInteger(POSITION_MAGIC) != InpMagic) continue;
        if (PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
        if (FindPositionMeta(ticket) >= 0) continue;
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        double diff = MathAbs(open_price - entry);
        if (diff < best_diff) {
            best_diff = diff;
            best_ticket = ticket;
        }
    }
    if (best_ticket == 0) return;
    int n = ArraySize(g_pos_tickets);
    ArrayResize(g_pos_tickets, n + 1);
    ArrayResize(g_pos_initial_risk, n + 1);
    ArrayResize(g_pos_atr, n + 1);
    ArrayResize(g_pos_open_time, n + 1);
    g_pos_tickets[n] = best_ticket;
    g_pos_initial_risk[n] = MathAbs(entry - sl);
    g_pos_atr[n] = atr;
    g_pos_open_time[n] = open_time;
}

void RemovePositionMetaAt(int idx) {
    int n = ArraySize(g_pos_tickets);
    if (idx < 0 || idx >= n) return;
    for (int i = idx; i < n - 1; i++) {
        g_pos_tickets[i] = g_pos_tickets[i + 1];
        g_pos_initial_risk[i] = g_pos_initial_risk[i + 1];
        g_pos_atr[i] = g_pos_atr[i + 1];
        g_pos_open_time[i] = g_pos_open_time[i + 1];
    }
    ArrayResize(g_pos_tickets, n - 1);
    ArrayResize(g_pos_initial_risk, n - 1);
    ArrayResize(g_pos_atr, n - 1);
    ArrayResize(g_pos_open_time, n - 1);
}

void CleanupPositionMeta() {
    for (int i = ArraySize(g_pos_tickets) - 1; i >= 0; i--) {
        if (!PositionSelectByTicket(g_pos_tickets[i])) {
            RemovePositionMetaAt(i);
        }
    }
}

bool ModifyPositionSl(ulong ticket, double new_sl, double tp) {
    MqlTradeRequest req = {};
    MqlTradeResult  res = {};
    req.action = TRADE_ACTION_SLTP;
    req.position = ticket;
    req.symbol = _Symbol;
    req.sl = new_sl;
    req.tp = tp;
    req.magic = InpMagic;
    bool ok = OrderSend(req, res);
    if (!ok || res.retcode > 10013) {
        if (InpVerbose)
            PrintFormat("Trailing modify FAILED ticket=%I64u ret=%d %s", ticket, res.retcode, res.comment);
        return false;
    }
    return true;
}

void UpdateTrailingStops() {
    if (!InpTrailingEnabled) return;
    int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
    double stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        ulong ticket = PositionGetTicket(i);
        if (ticket == 0 || !PositionSelectByTicket(ticket)) continue;
        if (PositionGetInteger(POSITION_MAGIC) != InpMagic) continue;
        if (PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

        int meta_idx = FindPositionMeta(ticket);
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        double sl = PositionGetDouble(POSITION_SL);
        double tp = PositionGetDouble(POSITION_TP);
        double initial_risk = (meta_idx >= 0) ? g_pos_initial_risk[meta_idx] : MathAbs(open_price - sl);
        double atr = (meta_idx >= 0) ? g_pos_atr[meta_idx] : (initial_risk / 1.5);
        if (initial_risk <= _Point || atr <= _Point) continue;

        long pos_type = PositionGetInteger(POSITION_TYPE);
        bool is_buy = (pos_type == POSITION_TYPE_BUY);
        double cur_price = is_buy ? bid : ask;
        double profit_r = is_buy ? (cur_price - open_price) / initial_risk : (open_price - cur_price) / initial_risk;
        if (profit_r < InpBreakevenRR) continue;

        double candidate = open_price;
        if (profit_r >= InpTrailActivationRR) {
            double trail_dist = atr * InpTrailAtrMultiple;
            candidate = is_buy ? (cur_price - trail_dist) : (cur_price + trail_dist);
            if (is_buy && candidate < open_price) candidate = open_price;
            if (!is_buy && candidate > open_price) candidate = open_price;
        }
        candidate = NormalizeDouble(candidate, digits);

        if (is_buy) {
            if (candidate <= sl + _Point) continue;
            if ((cur_price - candidate) < stops_level) continue;
        } else {
            if (sl > 0.0 && candidate >= sl - _Point) continue;
            if ((candidate - cur_price) < stops_level) continue;
        }
        ModifyPositionSl(ticket, candidate, tp);
    }

    CleanupPositionMeta();
}

bool CloseOnePosition(ulong ticket) {
    if (!PositionSelectByTicket(ticket)) return false;
    if (PositionGetInteger(POSITION_MAGIC) != InpMagic) return false;
    if (PositionGetString(POSITION_SYMBOL) != _Symbol) return false;

    long pos_type = PositionGetInteger(POSITION_TYPE);
    double volume = PositionGetDouble(POSITION_VOLUME);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

    MqlTradeRequest req = {};
    MqlTradeResult  res = {};
    req.action = TRADE_ACTION_DEAL;
    req.position = ticket;
    req.symbol = _Symbol;
    req.volume = volume;
    req.type = (pos_type == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;
    req.price = (pos_type == POSITION_TYPE_BUY) ? bid : ask;
    req.magic = InpMagic;
    req.comment = "AI_RISK_CLOSE";
    req.type_filling = ORDER_FILLING_FOK;
    req.deviation = 50;

    bool ok = OrderSend(req, res);
    if (!ok || res.retcode > 10013) {
        PrintFormat("Risk close FAILED ticket=%I64u ret=%d %s", ticket, res.retcode, res.comment);
        return false;
    }
    return true;
}

void CloseAllPositions() {
    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        ulong ticket = PositionGetTicket(i);
        if (ticket == 0) continue;
        CloseOnePosition(ticket);
    }
}

void UpdateTimeStops(datetime bar_time) {
    if (InpMaxHoldBars <= 0) return;
    int period_sec = PeriodSeconds(PERIOD_M5);
    if (period_sec <= 0) period_sec = 300;

    for (int i = PositionsTotal() - 1; i >= 0; i--) {
        ulong ticket = PositionGetTicket(i);
        if (ticket == 0 || !PositionSelectByTicket(ticket)) continue;
        if (PositionGetInteger(POSITION_MAGIC) != InpMagic) continue;
        if (PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

        int meta_idx = FindPositionMeta(ticket);
        datetime open_time = (meta_idx >= 0) ? g_pos_open_time[meta_idx] : (datetime)PositionGetInteger(POSITION_TIME);
        if (open_time <= 0 || bar_time <= open_time) continue;
        int held_bars = (int)((bar_time - open_time) / period_sec);
        if (held_bars >= InpMaxHoldBars) {
            if (InpVerbose)
                PrintFormat("TIME_STOP ticket=%I64u held_bars=%d max=%d", ticket, held_bars, InpMaxHoldBars);
            CloseOnePosition(ticket);
        }
    }
    CleanupPositionMeta();
}

bool CheckCircuitBreakers(datetime now_time) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double equity = AccountInfoDouble(ACCOUNT_EQUITY);
    if (g_initial_balance <= 0.0) g_initial_balance = balance;
    if (g_day_start_balance <= 0.0) g_day_start_balance = balance;
    if (g_peak_equity <= 0.0) g_peak_equity = equity;
    if (equity > g_peak_equity) g_peak_equity = equity;

    if (g_killed) return false;

    if (InpTargetBalanceStop > 0.0 && (balance >= InpTargetBalanceStop || equity >= InpTargetBalanceStop)) {
        g_killed = true;
        if (InpCloseOnStop) CloseAllPositions();
        if (now_time != g_last_stop_log) {
            PrintFormat("TARGET_STOP: balance=%.2f equity=%.2f target=%.2f",
                        balance, equity, InpTargetBalanceStop);
            g_last_stop_log = now_time;
        }
        return false;
    }

    double peak_dd_floor = g_peak_equity * (1.0 - InpMaxPeakDDKillPct / 100.0);
    if (InpMaxPeakDDKillPct > 0.0 && equity <= peak_dd_floor) {
        g_killed = true;
        if (InpCloseOnStop) CloseAllPositions();
        if (now_time != g_last_stop_log) {
            PrintFormat("PEAK_DD_KILL: equity %.2f <= %.2f (peak=%.2f, maxPeakDD=%.2f%%)",
                        equity, peak_dd_floor, g_peak_equity, InpMaxPeakDDKillPct);
            g_last_stop_log = now_time;
        }
        return false;
    }

    double dd_floor = g_initial_balance * (1.0 - InpMaxDDKillPct / 100.0);
    if (InpMaxDDKillPct > 0.0 && equity <= dd_floor) {
        g_killed = true;
        if (InpCloseOnStop) CloseAllPositions();
        if (now_time != g_last_stop_log) {
            PrintFormat("KILL_SWITCH: equity %.2f <= %.2f (initial=%.2f, maxDD=%.2f%%)",
                        equity, dd_floor, g_initial_balance, InpMaxDDKillPct);
            g_last_stop_log = now_time;
        }
        return false;
    }

    double daily_floor = g_day_start_balance * (1.0 - InpMaxDailyLoss / 100.0);
    double daily_loss_cap = g_day_start_balance * InpMaxDailyLoss / 100.0;
    if (InpMaxDailyLoss > 0.0 && (g_day_loss >= daily_loss_cap || equity <= daily_floor)) {
        g_day_blocked = true;
        if (InpCloseOnStop) CloseAllPositions();
        if (now_time != g_last_stop_log) {
            PrintFormat("DAILY_STOP: equity=%.2f floor=%.2f realized_loss=%.2f cap=%.2f",
                        equity, daily_floor, g_day_loss, daily_loss_cap);
            g_last_stop_log = now_time;
        }
        return false;
    }

    if (g_day_blocked) return false;
    return true;
}

//+------------------------------------------------------------------+
//| Utility: unrealized + realized daily loss                        |
//+------------------------------------------------------------------+
void UpdateDailyLoss(datetime bar_time) {
    datetime today_start = bar_time - (bar_time % 86400);
    if (today_start != g_today) {
        g_today    = today_start;
        g_day_loss = 0.0;
        g_day_start_balance = AccountInfoDouble(ACCOUNT_BALANCE);
        g_day_blocked = false;
    }
}

//+------------------------------------------------------------------+
//| Load CSV into g_signals array                                    |
//+------------------------------------------------------------------+
bool LoadCSV() {
    // FILE_COMMON: read from %AppData%\MetaQuotes\Terminal\Common\Files\
    // This works for ALL tester agents regardless of port number
    int fh = FileOpen(InpCSVFile, FILE_READ | FILE_TXT | FILE_ANSI | FILE_COMMON);
    if (fh == INVALID_HANDLE) {
        // Fallback: try agent-local Files dir
        fh = FileOpen(InpCSVFile, FILE_READ | FILE_TXT | FILE_ANSI);
    }
    if (fh == INVALID_HANDLE) {
        Print("ERROR: Cannot open CSV: ", InpCSVFile,
              "  | Put it in: ", TerminalInfoString(TERMINAL_COMMONDATA_PATH),
              "\\Files\\  (or agent MQL5\\Files\\)");
        return false;
    }

    ArrayResize(g_signals, MAX_SIGNALS);
    g_sig_count = 0;

    string line;
    bool first_line = true;

    while (!FileIsEnding(fh) && g_sig_count < MAX_SIGNALS) {
        line = FileReadString(fh);      // reads one line in FILE_TXT mode
        if (first_line) { first_line = false; continue; }  // skip header
        if (StringLen(line) < 15) continue;

        // Split CSV line by comma
        string parts[];
        int cnt = StringSplit(line, ',', parts);
        if (cnt < 6) continue;

        // Trim whitespace from time field
        string ts = parts[0];
        StringTrimLeft(ts);
        StringTrimRight(ts);
        if (StringLen(ts) < 10) continue;

        SignalRow row;
        row.signal_time = StringToTime(ts);
        long dir_long   = StringToInteger(parts[1]);
        row.direction   = (dir_long == -1) ? -1 : 1;
        row.entry_price = StringToDouble(parts[2]);
        row.sl_price    = StringToDouble(parts[3]);
        row.tp_price    = StringToDouble(parts[4]);
        row.atr         = StringToDouble(parts[5]);
        row.prob        = (cnt >= 7) ? StringToDouble(parts[6]) : 0.0;
        g_signals[g_sig_count] = row;
        g_sig_count++;
    }

    FileClose(fh);
    ArrayResize(g_signals, g_sig_count);
    PrintFormat("Loaded %d signals from %s", g_sig_count, InpCSVFile);
    return (g_sig_count > 0);
}

//+------------------------------------------------------------------+
//| Place market order                                               |
//+------------------------------------------------------------------+
bool PlaceTrade(int direction, double ref_entry_price, double sl_price, double tp_price, double atr) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    if (balance <= 0) return false;

    // --- Lot sizing: fixed fractional risk ---
    double ask     = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid     = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double entry   = (direction == 1) ? ask : bid;

    double ref_sl_dist = MathAbs(ref_entry_price - sl_price);
    double sl_dist = ref_sl_dist;
    if (sl_dist < _Point) return false;   // Guard: invalid SL distance
    double intended_rr = (ref_sl_dist > _Point) ? (MathAbs(tp_price - ref_entry_price) / ref_sl_dist) : 2.0;
    if (intended_rr <= 0.0) intended_rr = 2.0;

    double drift_r = direction * (entry - ref_entry_price) / ref_sl_dist;
    if (drift_r < InpMinEntryDriftR || drift_r > InpMaxEntryDriftR) {
        if (InpVerbose)
            PrintFormat("SKIP (entry drift): driftR=%.2f allowed=[%.2f, %.2f] entry=%.5f ref=%.5f",
                        drift_r, InpMinEntryDriftR, InpMaxEntryDriftR, entry, ref_entry_price);
        return false;
    }

    // Snap SL/TP to actual entry (direction-aware)
    double actual_sl, actual_tp;
    if (direction == 1) {
        actual_sl = entry - sl_dist;
        actual_tp = entry + sl_dist * intended_rr;
    } else {
        actual_sl = entry + sl_dist;
        actual_tp = entry - sl_dist * intended_rr;
    }

    // Normalize prices
    int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
    actual_sl = NormalizeDouble(actual_sl, digits);
    actual_tp = NormalizeDouble(actual_tp, digits);

    // Lot size from risk %, with hard per-order and total-exposure caps.
    double risk_pct = MathMin(InpRiskPct, InpMaxRiskPct);
    double tick_val  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    double risk_per_lot = PriceRiskAmount(1.0, entry, actual_sl);
    if (risk_per_lot <= 0.0) return false;

    double max_order_risk = balance * risk_pct / 100.0;
    double lot       = max_order_risk / risk_per_lot;
    double min_lot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
    double max_lot   = MathMin(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX), 5.0);
    double lot_step  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
    double min_lot_risk = PriceRiskAmount(min_lot, entry, actual_sl);
    if (min_lot_risk > max_order_risk * 1.001) {
        PrintFormat("SKIP (min lot risk cap): min_lot=%.2f risk=%.2f cap=%.2f entry=%.5f sl=%.5f",
                    min_lot, min_lot_risk, max_order_risk, entry, actual_sl);
        return false;
    }

    lot = MathFloor(lot / lot_step) * lot_step;
    if (lot < min_lot) lot = min_lot;
    lot = MathMin(lot, max_lot);

    double current_risk = PriceRiskAmount(lot, entry, actual_sl);
    if (current_risk > max_order_risk * 1.001) {
        double capped_lot = MathFloor((max_order_risk / risk_per_lot) / lot_step) * lot_step;
        if (capped_lot < min_lot) {
            PrintFormat("SKIP (risk cap): lot=%.2f risk=%.2f cap=%.2f", lot, current_risk, max_order_risk);
            return false;
        }
        lot = capped_lot;
        current_risk = PriceRiskAmount(lot, entry, actual_sl);
    }

    bool unknown_risk = false;
    double open_risk = TotalOpenRisk(unknown_risk);
    double max_total_risk = balance * InpMaxExposurePct / 100.0;
    if (unknown_risk) {
        Print("SKIP (unknown open position risk: missing SL)");
        return false;
    }
    if (InpMaxExposurePct > 0.0 && open_risk + current_risk > max_total_risk * 1.001) {
        PrintFormat("SKIP (exposure cap): open=%.2f new=%.2f cap=%.2f",
                    open_risk, current_risk, max_total_risk);
        return false;
    }

    // Margin safety check: cap lot if required margin > 90% of free margin
    ENUM_ORDER_TYPE ord_type = (direction == 1) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
    double req_margin = 0;
    double free_margin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
    if(OrderCalcMargin(ord_type, _Symbol, lot, (direction==1)?ask:bid, req_margin) && req_margin > free_margin * 0.90)
    {
        double scale = free_margin * 0.90 / req_margin;
        lot = MathFloor(lot * scale / lot_step) * lot_step;
        lot = MathMax(min_lot, lot);
        if(InpVerbose)
            PrintFormat("MarginCap: lot scaled to %.2f (req_margin=%.2f free=%.2f)", lot, req_margin, free_margin);
    }
    // Final margin check after scaling: skip if still can't afford minimum lot
    if(OrderCalcMargin(ord_type, _Symbol, lot, (direction==1)?ask:bid, req_margin) && req_margin > free_margin)
    {
        PrintFormat("SKIP (no margin): lot=%.2f req=%.2f free=%.2f", lot, req_margin, free_margin);
        return false;
    }

    // Validate stops
    double stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
    if (direction == 1) {
        if ((entry - actual_sl) < stops_level) actual_sl = entry - stops_level * 1.5;
        if ((actual_tp - entry) < stops_level) actual_tp = entry + stops_level * 1.5;
    } else {
        if ((actual_sl - entry) < stops_level) actual_sl = entry + stops_level * 1.5;
        if ((entry - actual_tp) < stops_level) actual_tp = entry - stops_level * 1.5;
    }
    actual_sl = NormalizeDouble(actual_sl, digits);
    actual_tp = NormalizeDouble(actual_tp, digits);

    MqlTradeRequest  req = {};
    MqlTradeResult   res = {};
    req.action    = TRADE_ACTION_DEAL;
    req.symbol    = _Symbol;
    req.volume    = lot;
    req.type      = (direction == 1) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
    req.price     = (direction == 1) ? ask : bid;
    req.sl        = actual_sl;
    req.tp        = actual_tp;
    req.magic     = InpMagic;
    req.comment   = "AI_CSV";
    req.type_filling = ORDER_FILLING_FOK;
    req.deviation = 30;

    bool ok = OrderSend(req, res);
    if (!ok || res.retcode > 10013) {
        PrintFormat("OrderSend FAILED: %d | %s | lot=%.2f sl=%.5f tp=%.5f",
                    res.retcode, res.comment, lot, actual_sl, actual_tp);
        return false;
    }
    if (InpVerbose)
        PrintFormat("TRADE %s lot=%.2f entry=%.5f sl=%.5f tp=%.5f prob=%.3f",
                    (direction==1)?"BUY":"SELL", lot, entry, actual_sl, actual_tp, 0.0);
    RegisterPositionMeta(entry, actual_sl, atr, iTime(_Symbol, PERIOD_M5, 0));
    return true;
}

//+------------------------------------------------------------------+
//| OnInit                                                           |
//+------------------------------------------------------------------+
int OnInit() {
    if (!LoadCSV()) return INIT_FAILED;
    g_sig_cursor = 0;
    g_last_bar   = 0;
    g_last_processed_signal_time = 0;
    if (InpSkipHistoricalSignalsOnInit) {
        datetime prev_bar = iTime(_Symbol, PERIOD_M5, 1);
        if (prev_bar > 0)
            g_last_processed_signal_time = prev_bar;
    }
    g_today      = 0;
    g_day_loss   = 0.0;
    g_initial_balance = AccountInfoDouble(ACCOUNT_BALANCE);
    g_day_start_balance = g_initial_balance;
    g_peak_equity = AccountInfoDouble(ACCOUNT_EQUITY);
    g_day_blocked = false;
    g_killed = false;
    ArrayResize(g_pos_tickets, 0);
    ArrayResize(g_pos_initial_risk, 0);
    ArrayResize(g_pos_atr, 0);
    ArrayResize(g_pos_open_time, 0);
    Print("AI_Signal_Reader initialized. Magic=", InpMagic);
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| OnDeinit                                                         |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
    ArrayFree(g_signals);
    ArrayFree(g_pos_tickets);
    ArrayFree(g_pos_initial_risk);
    ArrayFree(g_pos_atr);
    ArrayFree(g_pos_open_time);
}

//+------------------------------------------------------------------+
//| Main loop — fires on new M5 bar open                             |
//+------------------------------------------------------------------+
void OnTick() {
    datetime tick_time = TimeCurrent();
    UpdateDailyLoss(tick_time);
    if (!CheckCircuitBreakers(tick_time)) return;
    UpdateTrailingStops();

    // Only act on new bar
    datetime cur_bar = iTime(_Symbol, PERIOD_M5, 0);
    if (cur_bar == g_last_bar) return;
    g_last_bar = cur_bar;

    // Previous bar open_time (= signal_time in CSV, shifted to broker GMT+3)
    datetime prev_bar = iTime(_Symbol, PERIOD_M5, 1);

    if (InpReloadCsvOnNewBar) {
        if (!LoadCSV()) {
            Print("CSV reload failed; skipping bar fail-closed");
            return;
        }
        g_sig_cursor = 0;
    }

    // Update daily loss tracking
    UpdateDailyLoss(cur_bar);
    if (!CheckCircuitBreakers(cur_bar)) return;
    UpdateTimeStops(cur_bar);
    if (!CheckCircuitBreakers(cur_bar)) return;

    // --- Account-level daily loss check ---
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    if (g_day_loss >= balance * InpMaxDailyLoss / 100.0) {
        if (InpVerbose) Print("Daily loss limit hit, skipping bar");
        return;
    }

    // --- Max concurrent positions check ---
    if (CountOpenPositions() >= InpMaxPositions) return;

    // --- Advance cursor past old signals ---
    while (g_sig_cursor < g_sig_count &&
           g_signals[g_sig_cursor].signal_time < prev_bar)
        g_sig_cursor++;

    // --- Try all signals matching prev_bar ---
    for (int i = g_sig_cursor; i < g_sig_count; i++) {
        if (g_signals[i].signal_time > prev_bar) break;    // past match window
        if (g_signals[i].signal_time != prev_bar) continue; // time mismatch
        if (g_signals[i].signal_time <= g_last_processed_signal_time) continue;

        // Respect max positions
        if (CountOpenPositions() >= InpMaxPositions) break;

        int    dir = g_signals[i].direction;
        double ep  = g_signals[i].entry_price;
        double sl  = g_signals[i].sl_price;
        double tp  = g_signals[i].tp_price;

        PlaceTrade(dir, ep, sl, tp, g_signals[i].atr);
    }
    if (prev_bar > g_last_processed_signal_time)
        g_last_processed_signal_time = prev_bar;
}

//+------------------------------------------------------------------+
//| Track closed deals for daily loss                               |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest     &req,
                        const MqlTradeResult      &res) {
    if (trans.type != TRADE_TRANSACTION_DEAL_ADD) return;
    if (HistoryDealSelect(trans.deal)) {
        long deal_entry = HistoryDealGetInteger(trans.deal, DEAL_ENTRY);
        if (deal_entry != DEAL_ENTRY_OUT &&
            deal_entry != DEAL_ENTRY_INOUT &&
            deal_entry != DEAL_ENTRY_OUT_BY) {
            return;
        }
        double deal_profit = HistoryDealGetDouble(trans.deal, DEAL_PROFIT);
        if (deal_profit < 0.0) {
            g_day_loss += MathAbs(deal_profit);
        }
        PrintFormat("BALANCE_UPDATE balance=%.2f equity=%.2f profit=%.2f",
                    AccountInfoDouble(ACCOUNT_BALANCE),
                    AccountInfoDouble(ACCOUNT_EQUITY),
                    deal_profit);
    }
}
//+------------------------------------------------------------------+
